### PR TITLE
Rooms validate that the Origin header matches their registration

### PR DESCRIPTION
**Pull request by MarkNSweep**
Signed-off-by: Adam Pilkington <apilkington@uk.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-room/63)

### CODE REVIEW

**Comment by ebullient** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java, line 50 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJj1V0YZzMIq8C8TXW:-KFJj1V0YZzMIq8C8TXX:467022158) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java#L50)):*
Probably better as FINE or FINER -- info would flood logs when done per connection. If we want to show this as info, put this message out when the values are read from / registered with the DB.

---

*[room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java, line 83 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJiifQHzi55P9YPu6_:-KFJiifQHzi55P9YPu6a:-1834220804) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java#L83)):*
Assume we're treating this as an option then for _this_ room (sorry reviewing bottom up to see what you're doing).. 

---

*[room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java, line 107 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJeRormsb6gfAs5Qyl:-KFJeRormsb6gfAs5Qym:-842559014) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java#L107)):*
On second thought: why is this coming from JNDI? As a room attribute? I can see that it could come from configuration for initial registration: but I *could* register this completely separately.. you need to be getting this from the DB (and only setting with an env var if this server does the registration). 

I also don't believe this can be final. If you attempt periodically to test for changes to the map DB (for token revocation, for example), then this value would change.

Are you assuming an updated token would re-create the Room object instance?

---

*[room-wlpcfg/startup.sh, line 5 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJiNJWOlGb_fCnLEvI:-KFJiNJWOlGb_fCnLEvJ:820006209) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-wlpcfg/startup.sh#L5)):*
Why is this needed?

---

*[room-wlpcfg/servers/gameon-room/server.xml, line 31 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJdrxz9SCvwNwMctts:-KFJdry-3YMnO089ysdM:-984613053) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-wlpcfg/servers/gameon-room/server.xml#L31)):*
Why is this kayleigh? I don't understand. Shouldn't this be read/pulled from the DB config? I don't believe this will be a final value given keys could be revoked. (though perhaps that would mean a server.xml change from something external, such that an application restart would be more appropriate... 

Not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room/63)*

**Comment by MarkNSweep** [comment]
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java, line 50 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJj1V0YZzMIq8C8TXW:-KFJntKe_T1AViAk1Evm:404180598) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java#L50)):*
I agree that info will fill up the log, but the issue is that as a developer - if I'm basing my room authentication on this code, then I will need to see those messages whilst I get the implementation working, otherwise things will just silently fail. So should we show a more verbose starting point or a less verbose finishing point ?

---

*[room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java, line 83 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJiifQHzi55P9YPu6_:-KFKIcAqaw_aYJfmus5K:1545042269) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java#L83)):*
Yes, tokens are an optional value for each room that you register. It also keeps things compatible with existing room registrations.

---

*[room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java, line 107 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJeRormsb6gfAs5Qyl:-KFKUUbeyzB47__R3Pq_:193768838) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java#L107)):*
In our room implementations, it is the rooms themselves which do the registration which means that they get this value externally. I'm not sure I see why this has to come from a database, isn't the requirement not to hard code in the value, after which the room is free to get the data from wherever. There was existing configuration in JNDI so I added the room token in there, rather than introducing a new database and the client connectivity to it.

I envisage the room managing the token lifecycle, so if it changes, then it re-registers with a new token. The alternative would be for the room to tell map to remove / alter a token for an existing registration, at which point you might as well re-register.

I'm not sure I understand your test scenario for checking the token has been revoked. I think there is potentially a bigger scenario that I don't understand which is if I change a room registration what happens to any currently connected players e.g. I change the registered WS endpoint, which should have the same effect as changing the token.

---

*[room-wlpcfg/startup.sh, line 5 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJiNJWOlGb_fCnLEvI:-KFKWjIRw4EaSF-BGaB3:-481957556) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-wlpcfg/startup.sh#L5)):*
It isn't anymore, it was from the original origin checking code. For info, it is not particularly easier to determine the ip address for a docker container from inside that container (you get env vars for the other containers in the same compose group, but not yourself). This was how I was getting that value. I will remove it.

---

*[room-wlpcfg/servers/gameon-room/server.xml, line 31 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJdrxz9SCvwNwMctts:-KFKXWhOZ93qgbxXJhh-:1212426273) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-wlpcfg/servers/gameon-room/server.xml#L31)):*
See my earlier comment on why this isn't in a DB. The value is just an arbitrary string. I think the requirement is for the token to be held externally to the application code, and to keep it simple I put it in a JNDI entry. Revocation would be a server.xml change / restart, to again keep things simple. After discussing we can always do another PR to externalise the token in a DB if needed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room/63)*

**Comment by ebullient** [comment]
Reviewed 1 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java, line 50 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJj1V0YZzMIq8C8TXW:-KFKc1ld7YDY9pKmFyUb:-1912875035) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java#L50)):*
We can do that w/ trace enabled locally. The log class right now does elevate to INFO anyway (even if FINE/FINER/etc.) 

---

*[room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java, line 107 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJeRormsb6gfAs5Qyl:-KFKcNN5CJXGQNBmeJR-:-814837482) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java#L107)):*
Picture: multiple versions of the room are running live. For some reason, the token has been compromised and should be replaced.  All future connections to running rooms will fail, because the Mediator will fetch the record from the DB to see the new key, but the rooms will not (they will see the old key). Operations on the map are not required to be performed by the rooms themselves (they could be done only once).

---

*[room-wlpcfg/servers/gameon-room/server.xml, line 31 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-KFJdrxz9SCvwNwMctts:-KFKcr_2X4on408q6sVu:1262380718) ([raw file](https://github.com/gameontext/gameon-room/blob/1ea441b22a1a99da9e9a4b351c00a5e737a2323b/room-wlpcfg/servers/gameon-room/server.xml#L31)):*
I meant reading it from the existing Map registration, not creating another DB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room/63)*

**Comment by ebullient** [comment]
Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room/63)*

**Comment by ebullient** [comment]
Will continue in follow-on item

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room/63#-:-KFKd1YGq5o1nhmx8HAf:-950106365)*

**Pull request merged**
